#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

find "$DIR/docs/" -type f -iname "*.html" -exec sed -E -i '' \
's/^<!-- Generated by javadoc \([0-9]+\.[0-9]+\.[0-9]+\) on .*-->$/<!-- Generated by javadoc -->/' "{}" \;
